#!/bin/bash

cd /opt/jenkins

exec java \
    -Duser.home=/opt/jenkins/data \
    -Djenkins.install.runSetupWizard=false \
    -Djenkins.model.Jenkins.slaveAgentPort=50000 \
    -jar /opt/jenkins/jenkins.war